backend:
  name: github
  repo: THELOOK6/proprio-plus-website
  branch: main
  # The magic is here - use Netlify's built-in OAuth provider
  # No need for client IDs, secrets, or redirects
  # This works out of the box with Netlify's GitHub integration
  site_domain: groupeproprioplus.netlify.app

# Media settings
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Content collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Publish", name: "publish", widget: "boolean", default: true }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "legal"
    label: "Legal Pages"
    folder: "src/content/legal"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Last Updated", name: "lastUpdated", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "team"
    label: "Team Members"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Headshot", name: "headshot", widget: "image" }
      - { label: "Job Title", name: "jobTitle", widget: "string" }
      - { label: "Bio", name: "body", widget: "markdown", required: false }
      - { label: "Publish", name: "publish", widget: "boolean", default: true }
      - { label: "Order", name: "order", widget: "number", value_type: "int" }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - { label: "LinkedIn Username", name: "linkedinUsername", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "X (Twitter) URL", name: "xSocial", widget: "string", required: false }
      - { label: "X (Twitter) Username", name: "xSocialUsername", widget: "string", required: false }
      - { label: "GitHub URL", name: "github", widget: "string", required: false }
      - { label: "GitHub Username", name: "githubUsername", widget: "string", required: false }

  - name: "properties"
    label: "Properties"
    folder: "src/content/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Monthly Rent", name: "rent", widget: "number" }
      - { label: "Square Footage", name: "sqft", widget: "number" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Property ID", name: "propertyId", widget: "string" }
      - { label: "Bedrooms", name: "bedrooms", widget: "number" }
      - { label: "Bathrooms", name: "bathrooms", widget: "number" }
      - { label: "Total Rooms", name: "rooms", widget: "number" }
      - { label: "Year Built", name: "yearBuilt", widget: "number" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - label: "Images"
        name: "images"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
        required: false
      - label: "Agent Information"
        name: "agent"
        widget: "object"
        fields:
          - { label: "Agent Name", name: "name", widget: "string" }
          - { label: "Company", name: "company", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Agent Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "body", widget: "markdown" }
