backend:
  name: github
  branch: main  # Replace with your branch

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

auth:
  # Integrate Auth0 for login
  provider: auth0
  clientId: "YOUR_AUTH0_CLIENT_ID"
  domain: "YOUR_AUTH0_DOMAIN"
  redirectUri: "https://groupeproprioplus.netlify.app/admin"
